/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.raventictactoe;

import javax.swing.JOptionPane;

/**
 *
 * @author avery
 */
public class RockPaperScissorVisual extends javax.swing.JFrame {

    /**
     * Creates new form RockPaperScissorVisual
     */
    public RockPaperScissorVisual() {
        initComponents();
        int x;
        int y;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p1ScissorsButton = new javax.swing.JButton();
        p1RockButton = new javax.swing.JButton();
        p1PaperButton = new javax.swing.JButton();
        p2ScissorsButton = new javax.swing.JButton();
        p2RockButton = new javax.swing.JButton();
        p2PaperButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p2Picked = new javax.swing.JLabel();
        p1Picked = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Player 2");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setText("Player 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        p1ScissorsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p1ScissorsButton.setText("Scissors");
        p1ScissorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ScissorsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(p1ScissorsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 90));

        p1RockButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p1RockButton.setText("Rock");
        p1RockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1RockButtonActionPerformed(evt);
            }
        });
        jPanel1.add(p1RockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 90, 90));

        p1PaperButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p1PaperButton.setText("Paper");
        p1PaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1PaperButtonActionPerformed(evt);
            }
        });
        jPanel1.add(p1PaperButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 90, 90));

        p2ScissorsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p2ScissorsButton.setText("Scissors");
        p2ScissorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ScissorsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(p2ScissorsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 130, 90));

        p2RockButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p2RockButton.setText("Rock");
        p2RockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2RockButtonActionPerformed(evt);
            }
        });
        jPanel1.add(p2RockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 90, 90));

        p2PaperButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        p2PaperButton.setText("Paper");
        p2PaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2PaperButtonActionPerformed(evt);
            }
        });
        jPanel1.add(p2PaperButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 90, 90));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText(":Player 2 Selected");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setText("Player 1 Selected:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        p2Picked.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        p2Picked.setForeground(new java.awt.Color(0, 0, 153));
        p2Picked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(p2Picked, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 310, -1));

        p1Picked.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        p1Picked.setForeground(new java.awt.Color(204, 0, 0));
        p1Picked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(p1Picked, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 290, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 210, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p1RockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1RockButtonActionPerformed
        // TODO add your handling code here:
        p1Picked.setText("ROCK");
    }//GEN-LAST:event_p1RockButtonActionPerformed

    private void p1PaperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1PaperButtonActionPerformed
        p1Picked.setText("PAPER");
    }//GEN-LAST:event_p1PaperButtonActionPerformed

    private void p1ScissorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ScissorsButtonActionPerformed
        p1Picked.setText("SCISSORS");
    }//GEN-LAST:event_p1ScissorsButtonActionPerformed

    private void p2RockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2RockButtonActionPerformed
        // TODO add your handling code here:
        p2Picked.setText("ROCK");
    }//GEN-LAST:event_p2RockButtonActionPerformed

    private void p2PaperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2PaperButtonActionPerformed
        // TODO add your handling code here:
        p2Picked.setText("PAPER");
    }//GEN-LAST:event_p2PaperButtonActionPerformed

    private void p2ScissorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ScissorsButtonActionPerformed
        // TODO add your handling code here:
        p2Picked.setText("SCISSORS");
    }//GEN-LAST:event_p2ScissorsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String player1 = p1Picked.getText();
        String player2 = p2Picked.getText();
       
        String s1 = "ROCK";
        String s2 = "PAPER";
        String s3 = "SCISSORS";
        
        
        if (player1.matches(s1) && player2.matches(s2)) {
            JOptionPane.showMessageDialog(null, "Player 2 Wins");
        } else if (player1.matches(s1) && player2.matches(s3)) {
            JOptionPane.showMessageDialog(null, "Player 1 Wins");
        } else if (player1.matches(s2) && player2.matches(s1)) {
            JOptionPane.showMessageDialog(null, "Player 1 Wins");
        } else if (player1.matches(s2) && player2.matches(s3)) {
            JOptionPane.showMessageDialog(null, "Player 2 Wins");
       } else if (player1.matches(s3) && player2.matches(s1)) {
           JOptionPane.showMessageDialog(null, "Player 2 Wins");
       } else if (player1.matches(s3) && player2.matches(s2)) {
           JOptionPane.showMessageDialog(null, "Player 1 Wins");
       } else if (player1.matches(player2)) {
           JOptionPane.showMessageDialog(null, "IT'S A DRAW");
       } else {
           JOptionPane.showMessageDialog(null, "Invalid input");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RockPaperScissorVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton p1PaperButton;
    private javax.swing.JLabel p1Picked;
    private javax.swing.JButton p1RockButton;
    private javax.swing.JButton p1ScissorsButton;
    private javax.swing.JButton p2PaperButton;
    private javax.swing.JLabel p2Picked;
    private javax.swing.JButton p2RockButton;
    private javax.swing.JButton p2ScissorsButton;
    // End of variables declaration//GEN-END:variables
}
